spring:
  application:
    name: common-redis
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: abcd5f15-8194-45f6-bc9b-f9bc313275b6
        username: nacos
        password: nacos
  redis:
    database: 0 #redis数据库索引，默认为0
    host: 192.168.0.214 #redis服务器地址
    port: 6379 #redis服务器连接端口
    password: 123456 #redis服务器连接密码，默认为null
    timeout: 5000 #redis连接超时时间