server:
  port: 10012

spring:
  application:
    name: common-mongo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: abcd5f15-8194-45f6-bc9b-f9bc313275b6
        username: nacos
        password: nacos
  data:
    mongodb:
      uri: mongodb://own:123456@192.168.0.213:27017/own_mongo?authSource=admin&ssl=false&authSource=own_mongo



